### ISSUE TITLE
Rdio Navbar and layout overlapped on iPad, using native iPhone app

### ISSUE THREAD

**Issue by ChristopherRyanCruz** [rdio/api#99]
hi - i’m presenting your login api through my app (iPhone native) on a view controller with a hidden status bar - and on an iPad RDIO’s navigation bar is cut off. Apple has some new issues with iOS7 calculating a view’s layout sometimes, and recommends us to call this :

"

self.edgesForExtendedLayout = UIRectEdgeNone;

“

since RDIO's view controller for logging in is private I am not able to adjust your view(it only works when the status bar is visible. Is there any way you guys can push out a new version of the API with this change in mind?.
![ios simulator screen shot nov 8 2013 10 28 30 am](https://f.cloud.github.com/assets/5696733/1502978/99e9da4e-48a3-11e3-9e53-cac6facb04cc.png)

**Comment by dasevilla** [comment]
Are you running the latest version of the [iOS SDK](http://www.rdio.com/developers/docs/libraries/ios/)? We released a fix for the iOS 7 status bar. Checkout our [notes on iOS 7](http://www.rdio.com/developers/docs/libraries/ios/ref-ios-7/ref-ios-7/).

**Comment by ChristopherRyanCruz** [comment]
@dasevilla yes I am, and the issue is still being replicated even though I am pushing the auth view down.

**Comment by ChristopherRyanCruz** [comment]
@dasevilla are you guys calling self.edgesForExtendedLayout = UIRectEdgeNone ?? I had a similar layout issue on spotify's login view but after adding that directly onto their login view controller it fixed all layout issues

**Comment by ChristopherRyanCruz** [comment]
https://github.com/ChristopherRyanCruz/hello-ios-playback here's an app i produced on your sample application to reproduce the bug we're having. please run on any iOS iPad simulator or iPad device.

**Comment by rknLA** [comment]
Thanks for posting code that reproduces the issue.  I'll see what I can do to get this fixed in our next release.

**Comment by rknLA** [comment]
@ChristopherRyanCruz I've had a chance to investigate this a bit more, and the symptom you're seeing is related to running a non-Universal iPhone app on an iPad... Notice that the status bar is still present in your screenshot, and is present in the main view, even though it's set to be hidden.

The larger issue, though, is that the view expects the status bar to be visible, and behaves incorrectly when the app is set to Universal, or run on iPhone with the settings you've added.  It does look like something we'll be able to fix for the next release, but I don't have a timeline of when we'll release that right now.

**Comment by rknLA** [comment]
Out of curiousity, does setting the `View controller-based status bar appearance` flag in your Info.plist to `NO` break other functionality in your app?  Because setting that flag seems to fix the symptoms.

**Comment by ChristopherRyanCruz** [comment]
@rknLA thanks for checking it out.

and yes setting that flag will break some views in my app. I actually need the functionality to change the the appearance of my status bar- as some view controllers in my app do not use a status bar, while other  view controllers  in my app do.

**Comment by rknLA** [comment]
This is fixed in [v1.3.6](http://on.rdio.com/1hgwyRF)
